name: hyouka_browser
description: A native Flutter Android browser with search and ad blocking.
publish_to: "none"
version: 1.1.0+2
environment:
  sdk: ">=3.10.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  adblocker_webview: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
